name: Daily Rotation Tests

on:
  schedule:
    - cron: '0 5 * * *'  # Her gün saat 08:00'de çalışacak (UTC+3)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest
      
    - name: Setup GeckoDriver
      uses: browser-actions/setup-geckodriver@latest
      with:
        token: ${{ github.token }}
        
    - name: Build with Maven
      run: mvn -B clean compile
      
    - name: Run Daily Tests
      run: mvn -B test -Dtest=DailyRotationRunner
      env:
        DISPLAY: :99
        MOZ_HEADLESS: 1
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      
    - name: Generate Allure Report
      if: always()
      run: mvn allure:report
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          target/cucumber-reports
          target/site/allure-maven-plugin
          target/surefire-reports
          
    - name: Send Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Daily Test Results - ${{ github.repository }}
        to: ${{ secrets.RECIPIENT_EMAIL }}
        from: GitHub Actions
        body: |
          Daily Test Results for ${{ github.repository }}
          
          Date: ${{ steps.date.outputs.date }}
          Test Scenario: According to the day of week
          
          Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          Please check the attached test reports for details.
